swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /payment/balanceof:
    get:
      tags:
      - payment
      description: get Balance of Address
      operationId: PaymentController.GetBalanceof
      parameters:
      - in: query
        name: address
        description: the address you want to get
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Response'
        "403":
          description: is error
  /payment/earn:
    post:
      tags:
      - payment
      description: create request earn CNC
      operationId: PaymentController.Earn amount CNC to address
      parameters:
      - in: body
        name: body
        description: body for Earn
        required: true
        schema:
          $ref: '#/definitions/models.EarnRequest'
      responses:
        "201":
          description: ""
          schema:
            $ref: '#/definitions/models.Response'
        "403":
          description: body is empty
  /payment/owner:
    get:
      tags:
      - payment
      description: get Owner Contract
      operationId: PaymentController.GetOwner
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Address'
        "403":
          description: is empty
  /payment/totalsupply:
    get:
      tags:
      - payment
      description: get total Token Contract
      operationId: PaymentController.GetTotalSupply
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/.Int'
        "403":
          description: is empty
  /payment/transfer:
    post:
      tags:
      - payment
      description: create request tranfer
      operationId: PaymentController.Send amount CNC
      parameters:
      - in: body
        name: body
        description: body for Payment content
        required: true
        schema:
          $ref: '#/definitions/models.TransferRequest'
      responses:
        "201":
          description: ""
          schema:
            $ref: '#/definitions/models.Response'
        "403":
          description: body is empty
  /payment/transferfrom:
    post:
      tags:
      - payment
      description: create request tranfer
      operationId: PaymentController.Send amount CNC from to
      parameters:
      - in: body
        name: body
        description: body for Payment content
        required: true
        schema:
          $ref: '#/definitions/models.TransferFromRequest'
      responses:
        "201":
          description: ""
          schema:
            $ref: '#/definitions/models.Response'
        "403":
          description: body is empty
definitions:
  .Int:
    type: object
  .false:
    type: object
  models.Address:
    title: Address
    type: object
    properties:
      address:
        type: string
  models.EarnRequest:
    title: EarnRequest
    type: object
    properties:
      addr_to:
        type: string
      amount:
        type: integer
        format: int64
  models.ErrorResponse:
    title: ErrorResponse
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        $ref: '#/definitions/199.0xc4203158c0.false'
  models.Object:
    title: Object
    type: object
    properties:
      ObjectId:
        type: string
      PlayerName:
        type: string
      Score:
        type: integer
        format: int64
  models.Profile:
    title: Profile
    type: object
    properties:
      Address:
        type: string
      Age:
        type: integer
        format: int64
      Email:
        type: string
      Gender:
        type: string
  models.Response:
    title: Response
    type: object
    properties:
      data:
        $ref: '#/definitions/70.0xc420315830.false'
      error:
        $ref: '#/definitions/models.ErrorResponse'
  models.TransferFromRequest:
    title: TransferFromRequest
    type: object
    properties:
      addr_from:
        type: string
      addr_to:
        type: string
      amount:
        type: integer
        format: int64
  models.TransferRequest:
    title: TransferRequest
    type: object
    properties:
      addr_to:
        type: string
      amount:
        type: integer
        format: int64
  models.User:
    title: User
    type: object
    properties:
      Id:
        type: string
      Password:
        type: string
      Profile:
        $ref: '#/definitions/models.Profile'
      Username:
        type: string
tags:
- name: payment
  description: |
    PaymentController operations for Payment
